//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	policyv1alpha1 "github.com/kyverno/kyverno-json/pkg/apis/policy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionBindings) DeepCopyInto(out *ActionBindings) {
	*out = *in
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]Binding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionBindings.
func (in *ActionBindings) DeepCopy() *ActionBindings {
	if in == nil {
		return nil
	}
	out := new(ActionBindings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionCheck) DeepCopyInto(out *ActionCheck) {
	*out = *in
	if in.Check != nil {
		in, out := &in.Check, &out.Check
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionCheck.
func (in *ActionCheck) DeepCopy() *ActionCheck {
	if in == nil {
		return nil
	}
	out := new(ActionCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionCheckRef) DeepCopyInto(out *ActionCheckRef) {
	*out = *in
	out.FileRef = in.FileRef
	if in.Check != nil {
		in, out := &in.Check, &out.Check
		*out = (*in).DeepCopy()
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionCheckRef.
func (in *ActionCheckRef) DeepCopy() *ActionCheckRef {
	if in == nil {
		return nil
	}
	out := new(ActionCheckRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionClusters) DeepCopyInto(out *ActionClusters) {
	*out = *in
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(string)
		**out = **in
	}
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make(Clusters, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionClusters.
func (in *ActionClusters) DeepCopy() *ActionClusters {
	if in == nil {
		return nil
	}
	out := new(ActionClusters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionDryRun) DeepCopyInto(out *ActionDryRun) {
	*out = *in
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionDryRun.
func (in *ActionDryRun) DeepCopy() *ActionDryRun {
	if in == nil {
		return nil
	}
	out := new(ActionDryRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionEnv) DeepCopyInto(out *ActionEnv) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]Binding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionEnv.
func (in *ActionEnv) DeepCopy() *ActionEnv {
	if in == nil {
		return nil
	}
	out := new(ActionEnv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionExpectations) DeepCopyInto(out *ActionExpectations) {
	*out = *in
	if in.Expect != nil {
		in, out := &in.Expect, &out.Expect
		*out = make([]Expectation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionExpectations.
func (in *ActionExpectations) DeepCopy() *ActionExpectations {
	if in == nil {
		return nil
	}
	out := new(ActionExpectations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionFormat) DeepCopyInto(out *ActionFormat) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionFormat.
func (in *ActionFormat) DeepCopy() *ActionFormat {
	if in == nil {
		return nil
	}
	out := new(ActionFormat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionInlineResource) DeepCopyInto(out *ActionInlineResource) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionInlineResource.
func (in *ActionInlineResource) DeepCopy() *ActionInlineResource {
	if in == nil {
		return nil
	}
	out := new(ActionInlineResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionObject) DeepCopyInto(out *ActionObject) {
	*out = *in
	out.ObjectType = in.ObjectType
	out.ActionObjectSelector = in.ActionObjectSelector
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionObject.
func (in *ActionObject) DeepCopy() *ActionObject {
	if in == nil {
		return nil
	}
	out := new(ActionObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionObjectSelector) DeepCopyInto(out *ActionObjectSelector) {
	*out = *in
	out.ObjectName = in.ObjectName
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionObjectSelector.
func (in *ActionObjectSelector) DeepCopy() *ActionObjectSelector {
	if in == nil {
		return nil
	}
	out := new(ActionObjectSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionOutputs) DeepCopyInto(out *ActionOutputs) {
	*out = *in
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]Output, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionOutputs.
func (in *ActionOutputs) DeepCopy() *ActionOutputs {
	if in == nil {
		return nil
	}
	out := new(ActionOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionResourceRef) DeepCopyInto(out *ActionResourceRef) {
	*out = *in
	out.FileRef = in.FileRef
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = (*in).DeepCopy()
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionResourceRef.
func (in *ActionResourceRef) DeepCopy() *ActionResourceRef {
	if in == nil {
		return nil
	}
	out := new(ActionResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionTimeout) DeepCopyInto(out *ActionTimeout) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionTimeout.
func (in *ActionTimeout) DeepCopy() *ActionTimeout {
	if in == nil {
		return nil
	}
	out := new(ActionTimeout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Apply) DeepCopyInto(out *Apply) {
	*out = *in
	in.ActionBindings.DeepCopyInto(&out.ActionBindings)
	in.ActionClusters.DeepCopyInto(&out.ActionClusters)
	in.ActionDryRun.DeepCopyInto(&out.ActionDryRun)
	in.ActionExpectations.DeepCopyInto(&out.ActionExpectations)
	in.ActionOutputs.DeepCopyInto(&out.ActionOutputs)
	in.ActionResourceRef.DeepCopyInto(&out.ActionResourceRef)
	in.ActionTimeout.DeepCopyInto(&out.ActionTimeout)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Apply.
func (in *Apply) DeepCopy() *Apply {
	if in == nil {
		return nil
	}
	out := new(Apply)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Assert) DeepCopyInto(out *Assert) {
	*out = *in
	in.ActionBindings.DeepCopyInto(&out.ActionBindings)
	in.ActionCheckRef.DeepCopyInto(&out.ActionCheckRef)
	in.ActionClusters.DeepCopyInto(&out.ActionClusters)
	in.ActionTimeout.DeepCopyInto(&out.ActionTimeout)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Assert.
func (in *Assert) DeepCopy() *Assert {
	if in == nil {
		return nil
	}
	out := new(Assert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Binding) DeepCopyInto(out *Binding) {
	*out = *in
	if in.Compiler != nil {
		in, out := &in.Compiler, &out.Compiler
		*out = new(policyv1alpha1.Compiler)
		**out = **in
	}
	in.Value.DeepCopyInto(&out.Value)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Binding.
func (in *Binding) DeepCopy() *Binding {
	if in == nil {
		return nil
	}
	out := new(Binding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatchFinally) DeepCopyInto(out *CatchFinally) {
	*out = *in
	if in.Compiler != nil {
		in, out := &in.Compiler, &out.Compiler
		*out = new(policyv1alpha1.Compiler)
		**out = **in
	}
	if in.PodLogs != nil {
		in, out := &in.PodLogs, &out.PodLogs
		*out = new(PodLogs)
		(*in).DeepCopyInto(*out)
	}
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = new(Events)
		(*in).DeepCopyInto(*out)
	}
	if in.Describe != nil {
		in, out := &in.Describe, &out.Describe
		*out = new(Describe)
		(*in).DeepCopyInto(*out)
	}
	if in.Wait != nil {
		in, out := &in.Wait, &out.Wait
		*out = new(Wait)
		(*in).DeepCopyInto(*out)
	}
	if in.Get != nil {
		in, out := &in.Get, &out.Get
		*out = new(Get)
		(*in).DeepCopyInto(*out)
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(Delete)
		(*in).DeepCopyInto(*out)
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = new(Command)
		(*in).DeepCopyInto(*out)
	}
	if in.Script != nil {
		in, out := &in.Script, &out.Script
		*out = new(Script)
		(*in).DeepCopyInto(*out)
	}
	if in.Sleep != nil {
		in, out := &in.Sleep, &out.Sleep
		*out = new(Sleep)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatchFinally.
func (in *CatchFinally) DeepCopy() *CatchFinally {
	if in == nil {
		return nil
	}
	out := new(CatchFinally)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Clusters) DeepCopyInto(out *Clusters) {
	{
		in := &in
		*out = make(Clusters, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Clusters.
func (in Clusters) DeepCopy() Clusters {
	if in == nil {
		return nil
	}
	out := new(Clusters)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Command) DeepCopyInto(out *Command) {
	*out = *in
	in.ActionBindings.DeepCopyInto(&out.ActionBindings)
	in.ActionCheck.DeepCopyInto(&out.ActionCheck)
	in.ActionClusters.DeepCopyInto(&out.ActionClusters)
	in.ActionEnv.DeepCopyInto(&out.ActionEnv)
	in.ActionOutputs.DeepCopyInto(&out.ActionOutputs)
	in.ActionTimeout.DeepCopyInto(&out.ActionTimeout)
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WorkDir != nil {
		in, out := &in.WorkDir, &out.WorkDir
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Command.
func (in *Command) DeepCopy() *Command {
	if in == nil {
		return nil
	}
	out := new(Command)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Configuration) DeepCopyInto(out *Configuration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Configuration.
func (in *Configuration) DeepCopy() *Configuration {
	if in == nil {
		return nil
	}
	out := new(Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Configuration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationSpec) DeepCopyInto(out *ConfigurationSpec) {
	*out = *in
	out.Timeouts = in.Timeouts
	if in.Compiler != nil {
		in, out := &in.Compiler, &out.Compiler
		*out = new(policyv1alpha1.Compiler)
		**out = **in
	}
	if in.Parallel != nil {
		in, out := &in.Parallel, &out.Parallel
		*out = new(int)
		**out = **in
	}
	if in.NamespaceTemplateCompiler != nil {
		in, out := &in.NamespaceTemplateCompiler, &out.NamespaceTemplateCompiler
		*out = new(policyv1alpha1.Compiler)
		**out = **in
	}
	if in.NamespaceTemplate != nil {
		in, out := &in.NamespaceTemplate, &out.NamespaceTemplate
		*out = (*in).DeepCopy()
	}
	if in.RepeatCount != nil {
		in, out := &in.RepeatCount, &out.RepeatCount
		*out = new(int)
		**out = **in
	}
	if in.ForceTerminationGracePeriod != nil {
		in, out := &in.ForceTerminationGracePeriod, &out.ForceTerminationGracePeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.DelayBeforeCleanup != nil {
		in, out := &in.DelayBeforeCleanup, &out.DelayBeforeCleanup
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make(Clusters, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Catch != nil {
		in, out := &in.Catch, &out.Catch
		*out = make([]CatchFinally, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationSpec.
func (in *ConfigurationSpec) DeepCopy() *ConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Create) DeepCopyInto(out *Create) {
	*out = *in
	in.ActionBindings.DeepCopyInto(&out.ActionBindings)
	in.ActionClusters.DeepCopyInto(&out.ActionClusters)
	in.ActionDryRun.DeepCopyInto(&out.ActionDryRun)
	in.ActionExpectations.DeepCopyInto(&out.ActionExpectations)
	in.ActionOutputs.DeepCopyInto(&out.ActionOutputs)
	in.ActionResourceRef.DeepCopyInto(&out.ActionResourceRef)
	in.ActionTimeout.DeepCopyInto(&out.ActionTimeout)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Create.
func (in *Create) DeepCopy() *Create {
	if in == nil {
		return nil
	}
	out := new(Create)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultTimeouts) DeepCopyInto(out *DefaultTimeouts) {
	*out = *in
	out.Apply = in.Apply
	out.Assert = in.Assert
	out.Cleanup = in.Cleanup
	out.Delete = in.Delete
	out.Error = in.Error
	out.Exec = in.Exec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultTimeouts.
func (in *DefaultTimeouts) DeepCopy() *DefaultTimeouts {
	if in == nil {
		return nil
	}
	out := new(DefaultTimeouts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Delete) DeepCopyInto(out *Delete) {
	*out = *in
	in.ActionBindings.DeepCopyInto(&out.ActionBindings)
	in.ActionClusters.DeepCopyInto(&out.ActionClusters)
	in.ActionExpectations.DeepCopyInto(&out.ActionExpectations)
	in.ActionTimeout.DeepCopyInto(&out.ActionTimeout)
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(bool)
		**out = **in
	}
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(ObjectReference)
		(*in).DeepCopyInto(*out)
	}
	if in.DeletionPropagationPolicy != nil {
		in, out := &in.DeletionPropagationPolicy, &out.DeletionPropagationPolicy
		*out = new(v1.DeletionPropagation)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Delete.
func (in *Delete) DeepCopy() *Delete {
	if in == nil {
		return nil
	}
	out := new(Delete)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Describe) DeepCopyInto(out *Describe) {
	*out = *in
	in.ActionClusters.DeepCopyInto(&out.ActionClusters)
	out.ActionObject = in.ActionObject
	in.ActionTimeout.DeepCopyInto(&out.ActionTimeout)
	if in.ShowEvents != nil {
		in, out := &in.ShowEvents, &out.ShowEvents
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Describe.
func (in *Describe) DeepCopy() *Describe {
	if in == nil {
		return nil
	}
	out := new(Describe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Error) DeepCopyInto(out *Error) {
	*out = *in
	in.ActionBindings.DeepCopyInto(&out.ActionBindings)
	in.ActionCheckRef.DeepCopyInto(&out.ActionCheckRef)
	in.ActionClusters.DeepCopyInto(&out.ActionClusters)
	in.ActionTimeout.DeepCopyInto(&out.ActionTimeout)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Error.
func (in *Error) DeepCopy() *Error {
	if in == nil {
		return nil
	}
	out := new(Error)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Events) DeepCopyInto(out *Events) {
	*out = *in
	in.ActionClusters.DeepCopyInto(&out.ActionClusters)
	out.ActionFormat = in.ActionFormat
	out.ActionObjectSelector = in.ActionObjectSelector
	in.ActionTimeout.DeepCopyInto(&out.ActionTimeout)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Events.
func (in *Events) DeepCopy() *Events {
	if in == nil {
		return nil
	}
	out := new(Events)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Expectation) DeepCopyInto(out *Expectation) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = (*in).DeepCopy()
	}
	in.Check.DeepCopyInto(&out.Check)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Expectation.
func (in *Expectation) DeepCopy() *Expectation {
	if in == nil {
		return nil
	}
	out := new(Expectation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileRef) DeepCopyInto(out *FileRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileRef.
func (in *FileRef) DeepCopy() *FileRef {
	if in == nil {
		return nil
	}
	out := new(FileRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Get) DeepCopyInto(out *Get) {
	*out = *in
	in.ActionClusters.DeepCopyInto(&out.ActionClusters)
	out.ActionFormat = in.ActionFormat
	out.ActionObject = in.ActionObject
	in.ActionTimeout.DeepCopyInto(&out.ActionTimeout)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Get.
func (in *Get) DeepCopy() *Get {
	if in == nil {
		return nil
	}
	out := new(Get)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectName) DeepCopyInto(out *ObjectName) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectName.
func (in *ObjectName) DeepCopy() *ObjectName {
	if in == nil {
		return nil
	}
	out := new(ObjectName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
	out.ObjectType = in.ObjectType
	out.ObjectName = in.ObjectName
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectType) DeepCopyInto(out *ObjectType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectType.
func (in *ObjectType) DeepCopy() *ObjectType {
	if in == nil {
		return nil
	}
	out := new(ObjectType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Operation) DeepCopyInto(out *Operation) {
	*out = *in
	in.OperationBase.DeepCopyInto(&out.OperationBase)
	if in.Apply != nil {
		in, out := &in.Apply, &out.Apply
		*out = new(Apply)
		(*in).DeepCopyInto(*out)
	}
	if in.Assert != nil {
		in, out := &in.Assert, &out.Assert
		*out = new(Assert)
		(*in).DeepCopyInto(*out)
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = new(Command)
		(*in).DeepCopyInto(*out)
	}
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(Create)
		(*in).DeepCopyInto(*out)
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(Delete)
		(*in).DeepCopyInto(*out)
	}
	if in.Describe != nil {
		in, out := &in.Describe, &out.Describe
		*out = new(Describe)
		(*in).DeepCopyInto(*out)
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(Error)
		(*in).DeepCopyInto(*out)
	}
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = new(Events)
		(*in).DeepCopyInto(*out)
	}
	if in.Get != nil {
		in, out := &in.Get, &out.Get
		*out = new(Get)
		(*in).DeepCopyInto(*out)
	}
	if in.Patch != nil {
		in, out := &in.Patch, &out.Patch
		*out = new(Patch)
		(*in).DeepCopyInto(*out)
	}
	if in.PodLogs != nil {
		in, out := &in.PodLogs, &out.PodLogs
		*out = new(PodLogs)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(Proxy)
		(*in).DeepCopyInto(*out)
	}
	if in.Script != nil {
		in, out := &in.Script, &out.Script
		*out = new(Script)
		(*in).DeepCopyInto(*out)
	}
	if in.Sleep != nil {
		in, out := &in.Sleep, &out.Sleep
		*out = new(Sleep)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(Update)
		(*in).DeepCopyInto(*out)
	}
	if in.Wait != nil {
		in, out := &in.Wait, &out.Wait
		*out = new(Wait)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Operation.
func (in *Operation) DeepCopy() *Operation {
	if in == nil {
		return nil
	}
	out := new(Operation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationBase) DeepCopyInto(out *OperationBase) {
	*out = *in
	if in.ContinueOnError != nil {
		in, out := &in.ContinueOnError, &out.ContinueOnError
		*out = new(bool)
		**out = **in
	}
	if in.Compiler != nil {
		in, out := &in.Compiler, &out.Compiler
		*out = new(policyv1alpha1.Compiler)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationBase.
func (in *OperationBase) DeepCopy() *OperationBase {
	if in == nil {
		return nil
	}
	out := new(OperationBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Output) DeepCopyInto(out *Output) {
	*out = *in
	in.Binding.DeepCopyInto(&out.Binding)
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Output.
func (in *Output) DeepCopy() *Output {
	if in == nil {
		return nil
	}
	out := new(Output)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Patch) DeepCopyInto(out *Patch) {
	*out = *in
	in.ActionBindings.DeepCopyInto(&out.ActionBindings)
	in.ActionClusters.DeepCopyInto(&out.ActionClusters)
	in.ActionDryRun.DeepCopyInto(&out.ActionDryRun)
	in.ActionExpectations.DeepCopyInto(&out.ActionExpectations)
	in.ActionOutputs.DeepCopyInto(&out.ActionOutputs)
	in.ActionResourceRef.DeepCopyInto(&out.ActionResourceRef)
	in.ActionTimeout.DeepCopyInto(&out.ActionTimeout)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Patch.
func (in *Patch) DeepCopy() *Patch {
	if in == nil {
		return nil
	}
	out := new(Patch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodLogs) DeepCopyInto(out *PodLogs) {
	*out = *in
	in.ActionClusters.DeepCopyInto(&out.ActionClusters)
	out.ActionObjectSelector = in.ActionObjectSelector
	in.ActionTimeout.DeepCopyInto(&out.ActionTimeout)
	if in.Tail != nil {
		in, out := &in.Tail, &out.Tail
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodLogs.
func (in *PodLogs) DeepCopy() *PodLogs {
	if in == nil {
		return nil
	}
	out := new(PodLogs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Proxy) DeepCopyInto(out *Proxy) {
	*out = *in
	in.ActionClusters.DeepCopyInto(&out.ActionClusters)
	in.ActionOutputs.DeepCopyInto(&out.ActionOutputs)
	in.ActionTimeout.DeepCopyInto(&out.ActionTimeout)
	out.ObjectName = in.ObjectName
	out.ObjectType = in.ObjectType
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Proxy.
func (in *Proxy) DeepCopy() *Proxy {
	if in == nil {
		return nil
	}
	out := new(Proxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Scenario) DeepCopyInto(out *Scenario) {
	*out = *in
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]Binding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Scenario.
func (in *Scenario) DeepCopy() *Scenario {
	if in == nil {
		return nil
	}
	out := new(Scenario)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Script) DeepCopyInto(out *Script) {
	*out = *in
	in.ActionBindings.DeepCopyInto(&out.ActionBindings)
	in.ActionCheck.DeepCopyInto(&out.ActionCheck)
	in.ActionClusters.DeepCopyInto(&out.ActionClusters)
	in.ActionEnv.DeepCopyInto(&out.ActionEnv)
	in.ActionOutputs.DeepCopyInto(&out.ActionOutputs)
	in.ActionTimeout.DeepCopyInto(&out.ActionTimeout)
	if in.Shell != nil {
		in, out := &in.Shell, &out.Shell
		*out = new(string)
		**out = **in
	}
	if in.ShellArgs != nil {
		in, out := &in.ShellArgs, &out.ShellArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WorkDir != nil {
		in, out := &in.WorkDir, &out.WorkDir
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Script.
func (in *Script) DeepCopy() *Script {
	if in == nil {
		return nil
	}
	out := new(Script)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Sleep) DeepCopyInto(out *Sleep) {
	*out = *in
	out.Duration = in.Duration
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Sleep.
func (in *Sleep) DeepCopy() *Sleep {
	if in == nil {
		return nil
	}
	out := new(Sleep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepTemplate) DeepCopyInto(out *StepTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepTemplate.
func (in *StepTemplate) DeepCopy() *StepTemplate {
	if in == nil {
		return nil
	}
	out := new(StepTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StepTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepTemplateSpec) DeepCopyInto(out *StepTemplateSpec) {
	*out = *in
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]Binding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Try != nil {
		in, out := &in.Try, &out.Try
		*out = make([]Operation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Catch != nil {
		in, out := &in.Catch, &out.Catch
		*out = make([]CatchFinally, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Finally != nil {
		in, out := &in.Finally, &out.Finally
		*out = make([]CatchFinally, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Cleanup != nil {
		in, out := &in.Cleanup, &out.Cleanup
		*out = make([]CatchFinally, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepTemplateSpec.
func (in *StepTemplateSpec) DeepCopy() *StepTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(StepTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Test) DeepCopyInto(out *Test) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Test.
func (in *Test) DeepCopy() *Test {
	if in == nil {
		return nil
	}
	out := new(Test)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Test) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpec) DeepCopyInto(out *TestSpec) {
	*out = *in
	if in.FailFast != nil {
		in, out := &in.FailFast, &out.FailFast
		*out = new(bool)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(Timeouts)
		(*in).DeepCopyInto(*out)
	}
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(string)
		**out = **in
	}
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make(Clusters, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Skip != nil {
		in, out := &in.Skip, &out.Skip
		*out = new(bool)
		**out = **in
	}
	if in.Concurrent != nil {
		in, out := &in.Concurrent, &out.Concurrent
		*out = new(bool)
		**out = **in
	}
	if in.SkipDelete != nil {
		in, out := &in.SkipDelete, &out.SkipDelete
		*out = new(bool)
		**out = **in
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(bool)
		**out = **in
	}
	if in.Compiler != nil {
		in, out := &in.Compiler, &out.Compiler
		*out = new(policyv1alpha1.Compiler)
		**out = **in
	}
	if in.NamespaceTemplate != nil {
		in, out := &in.NamespaceTemplate, &out.NamespaceTemplate
		*out = (*in).DeepCopy()
	}
	if in.NamespaceTemplateCompiler != nil {
		in, out := &in.NamespaceTemplateCompiler, &out.NamespaceTemplateCompiler
		*out = new(policyv1alpha1.Compiler)
		**out = **in
	}
	if in.Scenarios != nil {
		in, out := &in.Scenarios, &out.Scenarios
		*out = make([]Scenario, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]Binding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]TestStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Catch != nil {
		in, out := &in.Catch, &out.Catch
		*out = make([]CatchFinally, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ForceTerminationGracePeriod != nil {
		in, out := &in.ForceTerminationGracePeriod, &out.ForceTerminationGracePeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.DelayBeforeCleanup != nil {
		in, out := &in.DelayBeforeCleanup, &out.DelayBeforeCleanup
		*out = new(v1.Duration)
		**out = **in
	}
	if in.DeletionPropagationPolicy != nil {
		in, out := &in.DeletionPropagationPolicy, &out.DeletionPropagationPolicy
		*out = new(v1.DeletionPropagation)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpec.
func (in *TestSpec) DeepCopy() *TestSpec {
	if in == nil {
		return nil
	}
	out := new(TestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestStep) DeepCopyInto(out *TestStep) {
	*out = *in
	if in.Use != nil {
		in, out := &in.Use, &out.Use
		*out = new(Use)
		(*in).DeepCopyInto(*out)
	}
	in.TestStepSpec.DeepCopyInto(&out.TestStepSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestStep.
func (in *TestStep) DeepCopy() *TestStep {
	if in == nil {
		return nil
	}
	out := new(TestStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestStepSpec) DeepCopyInto(out *TestStepSpec) {
	*out = *in
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(Timeouts)
		(*in).DeepCopyInto(*out)
	}
	if in.DeletionPropagationPolicy != nil {
		in, out := &in.DeletionPropagationPolicy, &out.DeletionPropagationPolicy
		*out = new(v1.DeletionPropagation)
		**out = **in
	}
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(string)
		**out = **in
	}
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make(Clusters, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SkipDelete != nil {
		in, out := &in.SkipDelete, &out.SkipDelete
		*out = new(bool)
		**out = **in
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(bool)
		**out = **in
	}
	if in.Compiler != nil {
		in, out := &in.Compiler, &out.Compiler
		*out = new(policyv1alpha1.Compiler)
		**out = **in
	}
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]Binding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Try != nil {
		in, out := &in.Try, &out.Try
		*out = make([]Operation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Catch != nil {
		in, out := &in.Catch, &out.Catch
		*out = make([]CatchFinally, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Finally != nil {
		in, out := &in.Finally, &out.Finally
		*out = make([]CatchFinally, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Cleanup != nil {
		in, out := &in.Cleanup, &out.Cleanup
		*out = make([]CatchFinally, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestStepSpec.
func (in *TestStepSpec) DeepCopy() *TestStepSpec {
	if in == nil {
		return nil
	}
	out := new(TestStepSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Timeouts) DeepCopyInto(out *Timeouts) {
	*out = *in
	if in.Apply != nil {
		in, out := &in.Apply, &out.Apply
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Assert != nil {
		in, out := &in.Assert, &out.Assert
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Cleanup != nil {
		in, out := &in.Cleanup, &out.Cleanup
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Exec != nil {
		in, out := &in.Exec, &out.Exec
		*out = new(v1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Timeouts.
func (in *Timeouts) DeepCopy() *Timeouts {
	if in == nil {
		return nil
	}
	out := new(Timeouts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Update) DeepCopyInto(out *Update) {
	*out = *in
	in.ActionBindings.DeepCopyInto(&out.ActionBindings)
	in.ActionClusters.DeepCopyInto(&out.ActionClusters)
	in.ActionDryRun.DeepCopyInto(&out.ActionDryRun)
	in.ActionExpectations.DeepCopyInto(&out.ActionExpectations)
	in.ActionOutputs.DeepCopyInto(&out.ActionOutputs)
	in.ActionResourceRef.DeepCopyInto(&out.ActionResourceRef)
	in.ActionTimeout.DeepCopyInto(&out.ActionTimeout)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Update.
func (in *Update) DeepCopy() *Update {
	if in == nil {
		return nil
	}
	out := new(Update)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Use) DeepCopyInto(out *Use) {
	*out = *in
	in.With.DeepCopyInto(&out.With)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Use.
func (in *Use) DeepCopy() *Use {
	if in == nil {
		return nil
	}
	out := new(Use)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wait) DeepCopyInto(out *Wait) {
	*out = *in
	in.ActionTimeout.DeepCopyInto(&out.ActionTimeout)
	out.ActionFormat = in.ActionFormat
	in.ActionClusters.DeepCopyInto(&out.ActionClusters)
	out.ActionObject = in.ActionObject
	in.WaitFor.DeepCopyInto(&out.WaitFor)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wait.
func (in *Wait) DeepCopy() *Wait {
	if in == nil {
		return nil
	}
	out := new(Wait)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitFor) DeepCopyInto(out *WaitFor) {
	*out = *in
	if in.Deletion != nil {
		in, out := &in.Deletion, &out.Deletion
		*out = new(WaitForDeletion)
		**out = **in
	}
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = new(WaitForCondition)
		(*in).DeepCopyInto(*out)
	}
	if in.JsonPath != nil {
		in, out := &in.JsonPath, &out.JsonPath
		*out = new(WaitForJsonPath)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitFor.
func (in *WaitFor) DeepCopy() *WaitFor {
	if in == nil {
		return nil
	}
	out := new(WaitFor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitForCondition) DeepCopyInto(out *WaitForCondition) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(Expression)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitForCondition.
func (in *WaitForCondition) DeepCopy() *WaitForCondition {
	if in == nil {
		return nil
	}
	out := new(WaitForCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitForDeletion) DeepCopyInto(out *WaitForDeletion) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitForDeletion.
func (in *WaitForDeletion) DeepCopy() *WaitForDeletion {
	if in == nil {
		return nil
	}
	out := new(WaitForDeletion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitForJsonPath) DeepCopyInto(out *WaitForJsonPath) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(Expression)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitForJsonPath.
func (in *WaitForJsonPath) DeepCopy() *WaitForJsonPath {
	if in == nil {
		return nil
	}
	out := new(WaitForJsonPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *With) DeepCopyInto(out *With) {
	*out = *in
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]Binding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new With.
func (in *With) DeepCopy() *With {
	if in == nil {
		return nil
	}
	out := new(With)
	in.DeepCopyInto(out)
	return out
}
