version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - /
      - /hack/controller-gen/
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
