linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - decorder
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - gci
    - gochecknoinits
    - gofmt
    - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - makezero
    - misspell
    - noctx
    - nolintlint
    - nosprintfhostport
    - staticcheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - usetesting
    - wastedassign
    - whitespace

run:
  timeout: 15m

output:
  sort-results: true

issues:
  exclude-files:
    - ".+\\.generated.go"
