version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - decorder
    - dogsled
    - durationcheck
    - errname
    - gochecknoinits
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - makezero
    - misspell
    - noctx
    - nolintlint
    - nosprintfhostport
    - thelper
    - tparallel
    - unconvert
    - usetesting
    - wastedassign
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .+\.generated.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .+\.generated.go
      - third_party$
      - builtin$
      - examples$
