version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: chainsaw
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: chainsaw
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/kyverno/chainsaw/pkg/version.BuildVersion={{ .Version }}
  - id: s390x
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - s390x
    binary: chainsaw
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/kyverno/chainsaw/pkg/version.BuildVersion={{ .Version }}
  - id: ppc64le
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - ppc64le
    binary: chainsaw
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/kyverno/chainsaw/pkg/version.BuildVersion={{ .Version }}

kos:
  - build: chainsaw
    base_image: cgr.dev/chainguard/kubectl:latest-dev
    repositories:
      - ghcr.io/kyverno/chainsaw
    tags:
      - '{{.Tag}}'
      - '{{ if not .Prerelease }}latest{{ end }}' 
    bare: true
    preserve_import_paths: false
    sbom: none
    platforms:
      - all
    labels:
      org.opencontainers.image.source: https://github.com/kyverno/chainsaw
      org.opencontainers.image.description: Chainsaw - declarative K8s e2e testing

signs:
  - cmd: cosign
    certificate: '${artifact}.pem'
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - --bundle=${signature}
      - ${artifact}
      - --yes
    artifacts: all
    output: true

docker_signs:
  - cmd: cosign
    artifacts: all
    output: true
    args:
      - sign
      - ${artifact}
      - --yes

brews:
  - homepage: https://kyverno.github.io/chainsaw
    description: Declarative Kubernetes end-to-end testing.
    repository:
      owner: kyverno
      name: chainsaw
      branch: brew-{{.Version}}
      pull_request:
        enabled: true
        base:
          owner: kyverno
          name: chainsaw
          branch: main

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: checksums.txt

source:
  enabled: true

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

snapshot:
  version_template: '{{ incpatch .Version }}-next'

release:
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
