# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chainsaw < Formula
  desc "Declarative Kubernetes end-to-end testing."
  homepage "https://kyverno.github.io/chainsaw"
  version "0.2.1"

  on_macos do
    on_intel do
      url "https://github.com/kyverno/chainsaw/releases/download/v0.2.1/chainsaw_darwin_amd64.tar.gz"
      sha256 "b9cbabfd7af07cc6104e5b1ec71716dcf823a86e99f0ea79fc4baace86871bca"

      def install
        bin.install "chainsaw"
      end
    end
    on_arm do
      url "https://github.com/kyverno/chainsaw/releases/download/v0.2.1/chainsaw_darwin_arm64.tar.gz"
      sha256 "0360abb07de1eee8546aeb419d36b77f4d2ab288842d1d8414cece56555390af"

      def install
        bin.install "chainsaw"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyverno/chainsaw/releases/download/v0.2.1/chainsaw_linux_amd64.tar.gz"
        sha256 "9264bb2f15c1b70009816d95b70f471f45febba6b90fe5f3c6ebf93eac5258bb"

        def install
          bin.install "chainsaw"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyverno/chainsaw/releases/download/v0.2.1/chainsaw_linux_arm64.tar.gz"
        sha256 "735ed35ab773dce0494090acfa54791e2df00d14c3662bb9bded1f0ef83e7856"

        def install
          bin.install "chainsaw"
        end
      end
    end
  end
end
