# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json

name: "Bug Report"
description: Report a bug in the chainsaw.
title: "[Bug]"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: Please tell us about the bug.
  - type: dropdown
    id: chainsaw-version
    attributes:
      label: chainsaw version Version
      description: What version of chainsaw are you running?
      options:
      - v0.2.11
      - v0.2.10
      - v0.2.9
      - v0.2.8
      - v0.2.7
      - v0.2.6
      - v0.2.5
      - v0.2.4
      - v0.2.3
      - v0.2.2
      - v0.2.1
      - v0.2.0
      - v0.1.9
      - v0.1.8
      - v0.1.7
      - v0.1.6
      - v0.1.5
      - v0.1.4
      - v0.1.3
      - v0.1.2
      - v0.1.1
      - v0.1.0
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: Describe what happened.
      # placeholder: Tell us what you see!
      # value: "asdf"
    validations:
      required: true
  - type: textarea
    id: bug-reproduce-steps
    attributes:
      label: Steps to reproduce
      description: >-
        What are the exact steps needed to reproduce the bug you experienced?
      # placeholder: Tell us what you see!
      value: |-
        1. 
    validations:
      required: true
  - type: textarea
    id: bug-expectations
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      # placeholder: Tell us what you see!
      # value: "asdf"
    validations:
      required: true
  - type: textarea
    id: bug-screenshots
    attributes:
      label: Screenshots
      description: >-
        If you have any screenshots that would help, please paste them below.
        GitHub allows you to copy-and-paste directly from the clipboard into the text area.
        **Please avoid taking screenshots of either log or terminal output**; paste any textual output in the logs section below.
      # placeholder: Tell us what you see!
      # value: "asdf"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: >-
        Please copy and paste any relevant log output. 
      render: Shell
  - type: input
    id: slack
    attributes:
      label: Slack discussion
      description: >-
        If this issue is the result of a discussion thread on Slack, please provide the link to the discussion for reference.
      # placeholder: ex. email@example.com
    validations:
      required: false
  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting
      description: >-
        By submitting this issue, you agree that you have performed some basic attempts at researching and solving your problem.
      options:
        - label: I have searched other issues in this repository and mine is not recorded.
          required: true