# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json

name: General Question
description: Ask a question or need support
title: '[Question] ' 
labels:
- question
body:
  - type: markdown
    attributes:
      value: Please answer these questions before submitting your issue. Thanks!
  - type: textarea
    id: describe-your-question
    attributes:
      label: Describe your question
      description: Provide details about your question or the support needed.
      placeholder: Type your question here...
    validations:
      required: true
  - type: dropdown
    id: chainsaw-version
    attributes:
      label: chainsaw version Version
      description: What version of chainsaw are you running?
      options:
      - v0.2.10
      - v0.2.9
      - v0.2.8
      - v0.2.7
      - v0.2.6
      - v0.2.5
      - v0.2.4
      - v0.2.3
      - v0.2.2
      - v0.2.1
      - v0.2.0
      - v0.1.9
      - v0.1.8
      - v0.1.7
      - v0.1.6
      - v0.1.5
      - v0.1.4
      - v0.1.3
      - v0.1.2
      - v0.1.1
      - v0.1.0
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the question here.
      placeholder: Additional details...
    validations:
      required: false
