authors:
  eddycharly:
    name: Charles-Edouard Brétéché
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/47974576
  shubham-cmyk:
    name:  Shubham Gupta
    description: Contributor
    avatar: https://avatars.githubusercontent.com/u/69793468